### PR TITLE
README warning that parse methods have not yet been implemented.

### PR DESCRIPTION
**Pull request by aholland**

### CODE REVIEW

**Comment by sjrd** [comment]
There are a bunch of things that have not been implemented yet. This warning would imply that everything else is implemented, which is false.

**Comment by aholland** [comment]
Could it be worth listing those too? This particular warning would have saved me quite a bit of time, because in an unfamiliar environment I thought the problem was something else.

**Comment by sjrd** [comment]
> Could it be worth listing those too?

The list is too big to write there. What about #11?

**Comment by nicolasstucki** [comment]
You could reference #7.

**Comment by aholland** [comment]
I'd be happy with #11. The class I fell down on (though in retrospect I should both have run my tests in Scala.JS and have read the error message more closely) was LocalDate. As that is ticked in #7 I think I'd find that a bit misleading.

**Comment by sjrd** [comment]
OK, superseded by #11, then. Thanks for your input!

**Pull request closed without merging**
